routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();



Route::get('admin/home','AdminController@index');
Route::get('admin','Admin\LoginController@showLoginForm')->name('admin.login');
Route::post('admin','Admin\LoginController@login');
Route::post('admin-password/email','Admin\ForgotPasswordController@sendResetLinkEmail')->name('admin.password.email');
Route::get('admin-password/reset','Admin\ForgotPasswordController@showLinkRequestForm')->name('admin.password.request');
Route::post('admin-password/reset','Admin\ResetPasswordController@reset');
Route::get('admin-password/reset/{token}','Admin\ResetPasswordController@showResetForm')->name('admin.password.reset');
Route::post('admin/logout','Admin\LoginController@logout')->name('admin.logout');

Route::group(['prefix'=>'admin','namespace'=>'Admin','middleware'=>['admin']],function(){

	//HOMEPAGE MENU ROUTES
	Route::resource('/slider','SliderController',['except'=>'destroy']);
	Route::post('/slider/delete',[
		'uses'	=> 'SliderController@delete',
		'as'	=> 'slider.delete',
	]);

	Route::post('/slider/order','SliderController@order')->name('slider.order');

	Route::resource('/testimonial','TestimonialController',['except'=>'destroy']);
	Route::post('/testimonial/delete',[
		'uses'	=> 'TestimonialController@delete',
		'as'	=> 'testimonial.delete',
	]);

	Route::resource('/generalinfo','GeneralInfoController');

	//MASTER MENU ROUTES

	Route::resource('/projectmaster','ProjectMasterController',['except'=>'destroy']);
	Route::post('/projectmaster/delete',[
		'uses'	=> 'ProjectMasterController@delete',
		'as'	=> 'projectmaster.delete',
	]);

	Route::resource('/cms','CmsController',['except'=>'destroy']);
	Route::post('/cms/delete',[
		'uses'	=> 'CmsController@delete',
		'as'	=> 'cms.delete',
	]);

	//CAREER MENU ROUTES

	Route::resource('/career','CareerController',['except'=>'destroy']);
	Route::post('/career/delete',[
		'uses'	=> 'CareerController@delete',
		'as'	=> 'career.delete',
	]);

	Route::resource('/technology','TechnologyController',['except'=>'destroy']);
	Route::post('/technology/delete',[
		'uses'	=> 'TechnologyController@delete',
		'as'	=> 'technology.delete',
	]);

	Route::resource('/educational','EducationalController',['except'=>'destroy']);
	Route::post('/educational/delete',[
		'uses'	=> 'EducationalController@delete',
		'as'	=> 'educational.delete',
	]);

	//SERVICES MENU ROUTES

	Route::resource('/servicemaster','ServiceMasterController',['except'=>'destroy']);
	Route::post('/servicemaster/delete',[
		'uses'	=> 'ServiceMasterController@delete',
		'as'	=> 'servicemaster.delete',
	]);

	Route::resource('/servicepart','ServiceInnerPartController',['except'=>'destroy']);
	Route::post('/servicepart/delete',[
		'uses'	=> 'ServiceInnerPartController@delete',
		'as'	=> 'servicepart.delete',
	]);


	//GALLARY ROUTES

	Route::resource('/clientlogo','ClientLogoController',['except'=>['destroy','edit','update','show']]);
	Route::get('/clientlogo/edit',[
		'uses' => 'ClientLogoController@edit',
		'as'	=> 'clientlogo.edit',
	]);
	Route::post('/clientlogo/update',[
		'uses' => 'ClientLogoController@update',
		'as'	=> 'clientlogo.update',
	]);
	Route::post('/clientlogo/delete',[
		'uses'	=> 'ClientLogoController@delete',
		'as'	=> 'clientlogo.delete',
	]);

	Route::resource('/projectgallery','ProjectGalleryController',['except'=>'destroy']);
	Route::post('/projectgallery/delete',[
		'uses'	=> 'ProjectGalleryController@delete',
		'as'	=> 'projectgallery.delete',
	]);

	Route::post('/projectmultigallery','ProjectGalleryController@deleteImage')->name('delete.image');

	//MENU ROUTES
	Route::get('menu','Themecontroller@index')->name('menu.get');

	//File Manager Routes
	Route::get('/laravel-filemanager', '\Unisharp\Laravelfilemanager\controllers\LfmController@show');
    Route::post('/laravel-filemanager/upload', '\Unisharp\Laravelfilemanager\controllers\UploadController@upload');

});


Route::group(['middleware' => 'set_active_menu'], function(){

	Route::get('/','Frontend\HomeController@index')->name('homepage.index');
	Route::get('/{slug}','Frontend\DetailsController@details')->name('details.get');

	Route::post('/contact-us','Frontend\ContactUsController@index');
	Route::post('/contact-us','Frontend\ContactUsController@SaveContact')->name('contact-us.store');

	//frontend service route
	Route::get('/service/{slug}','Frontend\DetailsController@getservices')->name('service.get');

	Route::resource('/frontend-career','Frontend\CareerController',['except'=>'destroy']);
	Route::post('/frontend-career/delete',[
		'uses'	=> 'Frontend\CareerController@delete',
		'as'	=> 'frontend-career.delete',
	]);

});

app/Http/Controllers/Admin/CareerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Career;
use Event;
use App\Events\CareerEvent;
use App\Http\Requests\CareerRequest;

class CareerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        // dd(Career::all());
        if ($request->ajax()) {
            $where_paramsstr = '1 = ?';
            $where_params = [1];

            if ($request->has('sSearch')) {
                $search = $request->get('sSearch');
                $where_paramsstr .= " and ( title like \"%{$search}%\")";
            }
            $user = Career::select('id','title','activetitle')
            ->whereRaw($where_paramsstr, $where_params);

            $user_count = Career::select('id')
            ->whereRaw($where_paramsstr, $where_params)
            ->count();

            $columns = ['id','title','activetitle'];

            if ($request->has('iDisplayStart') && $request->get('iDisplayLength') != '-1') {
                $user = $user->take($request->get('iDisplayLength'))->skip($request->get('iDisplayStart'));
            }

            if ($request->has('iSortCol_0')) {
                for ($i = 0; $i < $request->get('iSortingCols'); $i++) {
                    $column = $columns[$request->get('iSortCol_' . $i)];
                    if (false !== ($index = strpos($column, ' as '))) {
                        $column = substr($column, 0, $index);
                    }
                    $user = $user->orderBy($column, $request->get('sSortDir_' . $i));
                }
            }
            $user = $user->get();
            $response['iTotalDisplayRecords'] = $user_count;
            $response['iTotalRecords'] = $user_count;

            $response['sEcho'] = intval($request->get('sEcho'));

            $response['aaData'] = $user;

            return $response;
        }
        return view('admin.career.careermaster.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.career.careermaster.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CareerRequest $request)
    {
        $career_data = $request->all();
        // dd($career_data);
        Event::fire(new CareerEvent($career_data));

        if($request->save == 'add')
        {
            return redirect()->route('career.index')->with('message','Record added successfully..')->with('message_type','success');
        }
            return back()->with('message','Record added successfully..')->with('message_type','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
        $career_data = Career::find($id);
        $id = $career_data['id'];

        return view('admin.career.careermaster.edit',['career_data'=>$career_data,'id'=>$id]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(CareerRequest $request, $id)
    {
        $career_data = $request->all();
        $career_data['id'] = $id;

        Event::fire(new CareerEvent($career_data));
        if($request->save == 'Save')
        {
            return back()->with('message','Record Updated successfully')->with('message_type','success');
        }

        return redirect()->route('career.index')->with('message','Record Updated Successfully')->with('message_type','success');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function delete(Request $request)
    {
        $career_id = $request->get('id');
        //dd(count($career_id));
        if(count($career_id) > 1){
            foreach ($career_id as $key => $value) {
                Career::where('id', $value)->delete();
            }
        }
        else{
            Career::where('id', $career_id)->delete();
        }    
        return back()->with('message', 'Record deleted Successfully.')
            ->with('message_type', 'success');
    }
}

app/Http/Controllers/Frontend/CareerController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Frontend\Career;
use Event;
use App\Events\Frontend\CareerEvent;
use App\Model\Technology;
use App\Http\Requests\Frontend\CareerRequest;

class CareerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $technology_list = Technology::orderBy('technology_name','asc')->pluck('technology_name','id')->toArray();
        
        return view('frontend.career.index',compact('technology_list'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CareerRequest $request)
    {
        $career_data = $request->all();
        // dd($career_data);
        Event::fire(new CareerEvent($career_data));

        return back()->with('message','Record added successfully..')->with('message_type','success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/career/careermaster/create.blade.php
@extends('admin.layout.index')
@section('content')
<section class="content">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="box">
			    <div class="box-header with-border">
					<h3 class="box-title">Create Career</h3>
				</div>
				<br>
				<?= Form::open(['method'=>'post','route'=>'career.store','class'=>'form-horizontal','enctype'=>'multipart/form-data','files' => 'true'])?>
					<div class="box-body">
						<div class="form-group">
							<div class="col-sm-2 text-right">
								<?= Form::label('title','',['class'=>'control-label'])?><span class="text-danger"> *</span>
							</div>
							<div class="col-sm-8  @if($errors->has('title')) has-error @endif">
								<?= Form::text('title','',['class'=>'form-control','id'=>'title','placeholder'=>'Enter Title','maxlength'=>'50'])?>
								<div class="help-block">
			                        {{$errors->first('title')}}
			                    </div>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-2 text-right">
								<?= Form::label('Slug','',['class'=>'control-label'])?>
							</div>
							<div class="col-sm-8  @if($errors->has('slug')) has-error @endif">
								<?= Form::text('slug','',['class'=>'form-control','id'=>'slug','placeholder'=>'Enter Slug','maxlength'=>'50'])?>
								<div class="help-block">
									{{$errors->first('slug')}}
								</div>
                                <strong><small id="passwordHelpBlock" class="form-text text-muted">
                                    (Will be automatically generated from your title,if left empty)
                                </small></strong>
							</div>
						</div> 
						<div class="form-group">
			                <label for="fun" class="col-sm-2 control-label">Active/NotActive Title</label>
			                    <div class="col-md-8">
			                        <div class="input-group">
			                            <div id="radioBtn" class="btn-group">
			                                <a class="btn btn-primary btn-sm active" data-toggle="happy" data-title="active" id="title_active">Active</a>
			                                <a class="btn btn-primary btn-sm notActive" data-toggle="happy" data-title="notactive" id="title_notactive">Not Active</a>
			                            </div>
			                            <input type="hidden" name="activetitle" id="titlehidden" value="">
			                        </div>
			                        <span class='text-danger error'>{{ $errors->first('activetitle') }}</span>
			                    </div>
			                </div>
			                <div class="form-group">
                            	<label class="control-label col-md-2">Description<span class="text-danger"> *</span></label>
                            	<div class="col-md-8 @if($errors->has('description')) has-error @endif">
                                	<?= Form::textarea('description',old('description'),['class'=>'form-control','id'=>'editor1','rows'=>'4']) ?> 
                                	<span class='text-danger error'>{{ $errors->first('description') }}</span>
                            	</div>
                        	</div>
                        <div class="form-group">
                            <div class="col-sm-2 text-right">
                                <?= Form::label('Meta Title','',['class'=>'control-label'])?>
                            </div>
                            <div class="col-sm-8  @if($errors->has('metatitle')) has-error @endif">
                                <?= Form::text('metatitle','',['class'=>'form-control','id'=>'metatitle','placeholder'=>'Enter MetaTitle','maxlength'=>'50'])?>
                                <span class='text-danger error'>{{ $errors->first('metatitle') }}</span>
                            </div>
                        </div> 
                        <div class="form-group">
                            <label class="control-label col-md-2">Meta Description</label>
                            <div class="col-md-8 @if($errors->has('metadescription')) has-error @endif">
                                <?= Form::textarea('metadescription',old('metadescription'),['class'=>'form-control','id'=>'metadescription','rows'=>'4','placeholder'=>'Enter Meta Description']) ?> 
                                    <span class='text-danger error'>{{ $errors->first('metadescription') }}</span>
                            </div>
                        </div> 
                        <div class="form-group">
                            <label class="control-label col-md-2">Meta Keyword</label>
                            <div class="col-md-8 @if($errors->has('metakeyword')) has-error @endif">
                                <?= Form::textarea('metakeyword',old('metakeyword'),['class'=>'form-control','id'=>'metakeyword','rows'=>'4','placeholder'=>'Enter Meta Keyword']) ?> 
                                    <span class='text-danger error'>{{ $errors->first('metakeyword') }}</span>
                            </div>
                        </div>  
                    </div>
                    <div class="box-footer">
						<div class="form-group">
							<?= Form::label('','',['class'=>'col-sm-2 control-label'])?>
							<div class="col-sm-8 text-right">
								<button class="btn btn-primary" title="save" type="submit" name="save" value="add">Save</button>
								<button class="btn btn-primary" title="save & new" type="submi" name="save" value="new">Save & Create New Record</button>
								<a href="<?=URL::route('career.index')?>" title='Back'><button type="button" class="btn btn-default btn-sm" name="cancel">Back</button></a>
							</div>
						</div>       
					</div>
					<?= Form::close()?>
				</div>
			</div>
		</div>
	</div>
</section>
@stop

@section('css')
<style type="text/css">
    #radioBtn .notActive{
        color: #3276b1;
        background-color: #fff;
    }
    #radioBtn1 .notActive{
        color: #3276b1;
        background-color: #fff;
    }
</style>
@stop
@section('js')	
{{ Html::script("http://cdn.ckeditor.com/4.7.1/standard-all/ckeditor.js") }}
<script type="text/javascript">
	$('#radioBtn a').on('click', function(){
        var sel = $(this).data('title');
        var tog = $(this).data('toggle');
        $('#'+tog).prop('value', sel);
        $('#titlehidden').attr('value',sel);
        
        $('a[data-toggle="'+tog+'"]').not('[data-title="'+sel+'"]').removeClass('active').addClass('notActive');
        $('a[data-toggle="'+tog+'"][data-title="'+sel+'"]').removeClass('notActive').addClass('active');
    });
    $('#radioBtn1 a').on('click', function(){
        var sel = $(this).data('title');
        var tog = $(this).data('toggle');
        $('#'+tog).prop('value', sel);
        $('#subtitlehidden').attr('value',sel);
        
        $('a[data-toggle="'+tog+'"]').not('[data-title="'+sel+'"]').removeClass('active').addClass('notActive');
        $('a[data-toggle="'+tog+'"][data-title="'+sel+'"]').removeClass('notActive').addClass('active');
    });
    var data = "{{old('activetitle')}}";
    if(data == 'enable')
    {
        $("#title_active").addClass('active');
        $("#title_active").removeClass('notActive');
        $("#title_notactive").addClass('notActive');
        $("#title_notactive").removeClass('active');
    }
    else if(data == 'disable')
    { 
        $("#title_notactive").addClass('active');
    }
    $('#tbName').on('input change', function () {
            if ($(this).val() != '') {
                $('#submit').prop('disabled', false);
            }
            else {
                $('#submit').prop('disabled', true);
            }
        });

    //ckeditor...............
    CKEDITOR.config.extraPlugins = 'justify';
    CKEDITOR.replace( 'editor1', {
        height: 300,

    // Configure your file manager integration. This example uses CKFinder 3 for PHP.
    filebrowserImageBrowseUrl: '/admin/laravel-filemanager?type=Images',
    filebrowserImageUploadUrl: '/admin/laravel-filemanager/upload?type=Images&_token={{csrf_token()}}',
    filebrowserBrowseUrl: '/admin/laravel-filemanager?type=Files',
    filebrowserUploadUrl: '/admin/laravel-filemanager/upload?type=Files&_token={{csrf_token()}}',


    toolbar: [
    { name: 'basicstyles', items: [ 'Bold', 'Italic', 'Underline', 'Strike', 'Subscript', 'Superscript', '-', 'CopyFormatting', 'RemoveFormat' ] },
    { name: 'paragraph',  items: [ 'NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'Blockquote', 'CreateDiv', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', '-', 'BidiLtr', 'BidiRtl', 'Language' ] },
    { name: 'insert', items: [ 'Image', 'Flash', 'Table', 'HorizontalRule', 'Smiley', 'SpecialChar', 'PageBreak', 'Iframe' ] },
    // { name: 'alignment', items : [ 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock' ] },
    { name: 'clipboard',items : [ 'Cut','Copy','Paste','PasteText','PasteFromWord','-','Undo','Redo']},
    '/',
    { name: 'editing', items: [ 'Find', 'Replace', '-', 'SelectAll', '-', 'Scayt' ] },
    { name : 'links',items : ['Link','Unlink','Anchor']},
    { name: 'tools', items: [ 'Maximize', 'ShowBlocks' ] },
    { name: 'document', items: [ 'Source', '-', 'Save', 'NewPage', 'Preview', 'Print', '-', 'Templates' ] },
    { name: 'styles', items: [ 'Styles', 'Format', 'Font', 'FontSize' ] },
    { name: 'forms', items: [ 'Form', 'Checkbox', 'Radio', 'TextField', 'Textarea', 'Select', 'Button', 'ImageButton', 'HiddenField' ] },
    { name: 'colors', items: [ 'TextColor', 'BGColor' ] },
    { name: 'others', items: [ '-' ] },
    ],
    removeButtons: '',
    image_previewText: ' '
});
</script>
@include('admin.layout.alert')

@stop

resources/views/admin/career/careermaster/index.blade.php
@extends('admin.layout.index')
@section('content')
<section class="content">
        <h3>
            Career Master
        </h3>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header blue-border">
                        <div class="row">
                            <h3 class="box-title col-md-6 col-xs-12">Browse Career Information</h3>
                            <div class="text-right dropdown js__drop_down col-md-6 col-xs-12">
                                <a href="<?=route('career.create')?>" class="btn btn-primary btn-sm" title="Add New">Add New</a>
                                <a href="javascript:;" class="btn btn-danger delete_record btn-sm" title="Delete">Delete</a>
                            </div>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="table-responsive">
                            <table id="master_table" class="table table-striped table-bordered display" style="width:100%">
                                <thead>
                                    <tr>
                                        <th class="text-left">
                                            <div class="checkbox purple">
                                                <input type="checkbox" id="selectall1" class="select_check_box">
                                            </div>
                                        </th>
                                        <th>Title</th>
                                        <th>Active/NotActive</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th class="text-left">
                                            <div class="checkbox purple">
                                                <input type="checkbox" id="selectall1" class="select_check_box">
                                            </div>
                                        </th>
                                        <th>Title</th>
                                        <th>Active/NotActive</th>
                                        <th>Action</th>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>
@stop

@section('css')
{{ Html::style('backend/css/dataTables.bootstrap.css') }}
{{ Html::style('backend/css/dataTables.bootstrap.min.css') }}
{{ Html::style('backend/css/responsive.bootstrap.min.css') }}
{{ Html::style('backend/css/sweetalert.css') }}
@stop

@section('js')
{{ Html::script('backend/js/jquery.dataTables.min.js') }}
{{ Html::script('backend/js/dataTables.bootstrap.min.js') }}
{{ Html::script('backend/js/fnStandingRedraw.js') }}
{{ Html::script('backend/js/dataTables.responsive.min.js') }}
{{ Html::script('backend/js/sweetalert.min.js') }}
{{ Html::script("backend/js/delete_script.js") }}

<script type="text/javascript">

    var title = "Are you sure to delete selected record(s)?";
    var text = "You will not be able to recover this record";
    var type = "warning";
    var delete_path = "{{ URL::route('career.delete')}}";
    var token = "{{ csrf_token() }}";

    $('.delete_record').click(function(){
        var delete_id = $('#master_table tbody input[type=checkbox]:checked');
        checkLength(delete_id);
    });

    $(document).ready(function()
    {
        var master = $('#master_table').dataTable({
            bProcessing: false,
            bServerSide: true,
            autoWidth: true,
            stateSave: true,
            aaSorting: [
            [1, 'asc']
            ],
            sAjaxSource: "{{ URL::route('career.index')}}",
            fnServerParams: function ( aoData ) {
                aoData.push({ "name": "act", "value": "fetch" });
                server_params = aoData;
            },
            aoColumns: [
            {
                mData: "id",
                bSortable: false,
                bVisible: true,
                sWidth: "3%",
                sClass: 'text-center',
                mRender: function(v, t, o)
                {
                    return '<div class="checkbox purple">'
                    +'<input type="checkbox" id="chk_'+v+'" name="id[]" value="'+v+'"/>'
                    +'<label for="chk_'+v+'" style="min-height: 14px; padding-left:"></label>'
                    +'</div>';
                }
            },
            { "mData": "title",sWidth: "17%",bSortable: true,


            },
            { "mData": "activetitle",sWidth: "10%",bSortable: false,
                    mRender: function(v, t, o)
                    {
                        if(v == 'notactive')
                        {
                            var active_string = "<label class='label label-danger'>NotActive</label>";
                        }
                        else{
                            var active_string = "<label class='label label-success'>Active</label>";
                        }
                        return active_string;
                    }
            },
                        
        {
            mData: null,
            bSortable: false,
            sWidth: "7%",
            sClass: "text-center",
            mRender: function(v, t, o) {

                var editurl = "{{ route('career.edit',':id')}}";
                editurl = editurl.replace(':id',o['id']);


                var act_html = "<div class='btn-group'>"
                +"<a href='"+editurl+"'class='btn btn-default btn-sm'><i class='fa fa-pencil' title='Edit Record'></i></a>"
                +"<a href='javascript:void(0)' onclick=\"deleteRecord('"+delete_path+"','"+title+"','"+text+"','"+token+"','"+type+"',"+o['id']+")\"class='btn btn-default btn-sm'><i class='fa fa-trash' title='Delete Record'></a>"
                +"</div>"
                return act_html;
            }
        },
        ],
        fnPreDrawCallback : function() {
        },
        fnDrawCallback : function (oSettings) {
        }
    });

        master.fnSetFilteringDelay(1000);
    });
    $(".select_check_box").on('click', function(){
        var is_checked = $(this).is(':checked');
        $(this).closest('table').find('tbody tr td:first-child input[type=checkbox]').prop('checked',is_checked);
        $(".select_check_box").prop('checked',is_checked);
    });
</script>

@include('admin.layout.alert')
@stop